INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (1, 1, 1, '2025-03-25', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (2, 1, 3, '2025-03-25', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (3, 2, 3, '2025-03-28', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (4, 2, 4, '2025-03-28', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (5, 3, 5, '2025-03-11', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (6, 3, 7, '2025-03-11', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (7, 4, 1, '2025-03-20', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (8, 4, 8, '2025-03-20', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (9, 5, 11, '2025-03-15', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (10, 5, 13, '2025-03-15', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (11, 6, 14, '2025-03-19', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (12, 6, 2, '2025-03-19', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (13, 7, 2, '2025-03-13', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (14, 7, 15, '2025-03-13', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (15, 8, 1, '2025-03-30', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (16, 8, 3, '2025-03-30', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (17, 9, 5, '2025-03-19', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (18, 9, 8, '2025-03-19', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (19, 10, 9, '2025-03-17', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (20, 10, 12, '2025-03-17', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (21, 11, 14, '2025-03-26', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (22, 11, 11, '2025-03-26', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (23, 12, 2, '2025-03-14', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (24, 12, 3, '2025-03-14', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (25, 13, 5, '2025-03-09', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (26, 13, 7, '2025-03-09', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (27, 14, 9, '2025-04-03', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (28, 14, 10, '2025-04-03', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (29, 15, 10, '2025-03-04', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (30, 15, 11, '2025-03-04', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (31, 16, 14, '2025-04-05', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (32, 16, 5, '2025-04-05', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (33, 17, 6, '2025-02-27', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (34, 17, 7, '2025-02-27', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (35, 18, 4, '2025-02-28', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (36, 18, 8, '2025-02-28', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (37, 19, 9, '2025-02-25', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (38, 19, 11, '2025-02-25', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (39, 20, 1, '2025-03-27', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (40, 20, 3, '2025-03-27', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (41, 21, 7, '2025-04-11', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (42, 21, 2, '2025-04-11', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (43, 22, 5, '2025-03-30', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (44, 22, 9, '2025-03-30', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (45, 23, 1, '2025-03-24', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (46, 23, 10, '2025-03-24', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (47, 24, 3, '2025-03-28', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (48, 24, 2, '2025-03-28', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (49, 25, 6, '2025-03-23', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (50, 25, 7, '2025-03-23', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (51, 26, 6, '2025-04-02', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (52, 26, 9, '2025-04-02', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (53, 27, 13, '2025-03-31', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (54, 27, 15, '2025-03-31', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (55, 28, 3, '2025-03-05', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (56, 28, 2, '2025-03-05', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (57, 29, 1, '2025-03-21', 'was absent');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (58, 29, 7, '2025-03-21', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (59, 30, 5, '2025-04-05', 'attended');
INSERT INTO classenrollments (enrollment_id, schedule_id, client_id, enrollment_date, status) VALUES (60, 30, 9, '2025-04-05', 'attended');
